# Generated by Django 2.2.10 on 2020-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervoe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=20)),
                ('src', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
