# Generated by Django 2.2.10 on 2020-04-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervoe', '0002_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='LK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('film_name', models.CharField(max_length=200)),
                ('ryad', models.CharField(max_length=20)),
                ('mesto', models.CharField(max_length=20)),
            ],
        ),
    ]
